# Generated by Django 4.2.7 on 2023-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movies_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='m_desc',
            field=models.TextField(default='none'),
        ),
    ]
